name: Build and Package

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        env:
          NODE_ENV: development

      - name: Build application
        run: npm run build

      - name: Package for Windows
        run: npm run dist:win

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/*.exe
          retention-days: 30

      - name: Upload Windows portable artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-portable-build
          path: dist/*-portable.exe
          retention-days: 30

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        env:
          NODE_ENV: development

      - name: Build application
        run: npm run build

      - name: Package for macOS
        run: npm run dist:mac

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: dist/*.dmg
          retention-days: 30

      - name: Upload macOS ZIP artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-zip-build
          path: dist/*.zip
          retention-days: 30

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        env:
          NODE_ENV: development

      - name: Build application
        run: npm run build

      - name: Package for Linux
        run: npm run dist:linux

      - name: Upload Linux AppImage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-appimage-build
          path: dist/*.AppImage
          retention-days: 30

      - name: Upload Linux DEB artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-deb-build
          path: dist/*.deb
          retention-days: 30

      - name: Upload Linux TAR.GZ artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-tar-build
          path: dist/*.tar.gz
          retention-days: 30